require('vadym.options')
require('vadym.keymaps')
require('vadym.plugins')
require('vadym.colorscheme')
require('vadym.cmp')
require("vadym.lsp")
require("vadym.telescope")
require("vadym.treesitter")
require("vadym.autopairs")
require("vadym.lualine")
--require('vadym.autosave')

